steps:
  - name: python
    entrypoint: bash
    args:
      - '-c'
      - |
        pip install --upgrade platformio
        pio run
    dir: .
  - name: 'gcr.io/cloud-builders/gsutil'
    entrypoint: bash
    dir: .
    args:
      - '-c'
      - |
        gsutil mv /workspace/.pio/build/esp32/firmware.bin /workspace/.pio/build/esp32/firmware_esp32.bin
artifacts:
  objects:
    location: 'gs://$PROJECT_ID-firmwares/$TAG_NAME'
    paths:
      - /workspace/.pio/build/esp32/firmware_esp32.bin
